'use client';

import { use } from 'react';
import Link from 'next/link';

const reportData = {
  'rpt-001': { title: 'Q1 2026 Revenue Summary', type: 'Revenue', date: 'March 31, 2026', author: 'System (Auto-generated)' },
  'rpt-002': { title: 'Client Acquisition Analysis', type: 'Client', date: 'March 28, 2026', author: 'Sarah Mitchell' },
  'rpt-003': { title: 'Monthly Performance Review — March', type: 'Performance', date: 'March 25, 2026', author: 'System (Auto-generated)' },
  'rpt-004': { title: 'Annual Forecast 2026', type: 'Revenue', date: 'March 20, 2026', author: 'David Chen' },
  'rpt-005': { title: 'Client Retention Deep Dive', type: 'Client', date: 'March 18, 2026', author: 'Sarah Mitchell' },
  'rpt-006': { title: 'Sales Pipeline Efficiency', type: 'Performance', date: 'March 15, 2026', author: 'Alex Rivera' },
  'rpt-007': { title: 'Revenue by Region — Q1', type: 'Revenue', date: 'March 12, 2026', author: 'System (Scheduled)' },
  'rpt-008': { title: 'Custom KPI Dashboard Export', type: 'Custom', date: 'March 10, 2026', author: 'Admin' },
  'rpt-009': { title: 'Client Lifetime Value Report', type: 'Client', date: 'March 8, 2026', author: 'Sarah Mitchell' },
  'rpt-010': { title: 'Team Performance Scorecard — Q1', type: 'Performance', date: 'March 5, 2026', author: 'System (Auto-generated)' },
};

const typeBadgeStyles = {
  Revenue: 'bg-emerald-50 text-emerald-700 dark:bg-emerald-500/10 dark:text-emerald-400',
  Client: 'bg-blue-50 text-blue-700 dark:bg-blue-500/10 dark:text-blue-400',
  Performance: 'bg-violet-50 text-violet-700 dark:bg-violet-500/10 dark:text-violet-400',
  Custom: 'bg-amber-50 text-amber-700 dark:bg-amber-500/10 dark:text-amber-400',
};

const keyMetrics = [
  { metric: 'Total Revenue', value: '$48,235', change: '+12.5%', positive: true },
  { metric: 'New Clients', value: '23', change: '+15.0%', positive: true },
  { metric: 'Client Retention', value: '94.2%', change: '+1.8%', positive: true },
  { metric: 'Avg Deal Size', value: '$2,150', change: '-2.1%', positive: false },
  { metric: 'Sales Cycle (days)', value: '18', change: '-3 days', positive: true },
  { metric: 'MRR Growth', value: '$6,420', change: '+8.3%', positive: true },
  { metric: 'Customer LTV', value: '$12,800', change: '+5.6%', positive: true },
  { metric: 'Support Tickets', value: '42', change: '-18.0%', positive: true },
];

const recommendations = [
  'Increase investment in direct sales channel, which shows the highest ROI at 3.2x.',
  'Address the declining average deal size by introducing premium service tiers.',
  'Scale referral program, which grew 32% this quarter with minimal ad spend.',
  'Implement automated follow-up sequences for leads in the 15-30 day pipeline stage.',
  'Consider expanding into the Southeast region, which shows untapped potential based on demographic analysis.',
];

export default function ReportDetailPage({ params }) {
  const { id } = use(params);
  const report = reportData[id] || {
    title: 'Report Not Found',
    type: 'Custom',
    date: 'Unknown',
    author: 'Unknown',
  };

  return (
    <div className="min-h-screen bg-zinc-50 dark:bg-zinc-950">
      <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8 py-8">
        {/* Back Button */}
        <Link
          href="/analytics/reports"
          className="inline-flex items-center gap-1.5 text-sm text-zinc-500 hover:text-zinc-700 dark:text-zinc-400 dark:hover:text-zinc-200 transition-colors mb-6"
        >
          <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M15 19l-7-7 7-7" />
          </svg>
          Back to Reports
        </Link>

        {/* Report Header */}
        <div className="rounded-xl border border-zinc-200 bg-white shadow-sm dark:border-zinc-700 dark:bg-zinc-900 mb-6">
          <div className="px-6 py-5 sm:px-8 sm:py-6">
            <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-4">
              <div>
                <div className="flex items-center gap-2 mb-2">
                  <span className={`inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium ${typeBadgeStyles[report.type]}`}>
                    {report.type}
                  </span>
                  <span className="text-xs text-zinc-500 dark:text-zinc-400">{report.date}</span>
                </div>
                <h1 className="text-2xl font-bold text-zinc-900 dark:text-zinc-100">{report.title}</h1>
                <p className="mt-1 text-sm text-zinc-500 dark:text-zinc-400">
                  Generated by {report.author}
                </p>
              </div>
              <div className="flex items-center gap-2">
                <button className="inline-flex items-center gap-1.5 rounded-lg border border-zinc-200 bg-white px-3 py-2 text-sm font-medium text-zinc-700 hover:bg-zinc-50 dark:border-zinc-700 dark:bg-zinc-800 dark:text-zinc-300 dark:hover:bg-zinc-700 transition-colors">
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                  </svg>
                  Download
                </button>
                <button className="inline-flex items-center gap-1.5 rounded-lg border border-zinc-200 bg-white px-3 py-2 text-sm font-medium text-zinc-700 hover:bg-zinc-50 dark:border-zinc-700 dark:bg-zinc-800 dark:text-zinc-300 dark:hover:bg-zinc-700 transition-colors">
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.368 2.684 3 3 0 00-5.368-2.684z" />
                  </svg>
                  Share
                </button>
                <button className="inline-flex items-center gap-1.5 rounded-lg border border-zinc-200 bg-white px-3 py-2 text-sm font-medium text-zinc-700 hover:bg-zinc-50 dark:border-zinc-700 dark:bg-zinc-800 dark:text-zinc-300 dark:hover:bg-zinc-700 transition-colors">
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
                  </svg>
                  Print
                </button>
              </div>
            </div>
          </div>
        </div>

        {/* Report Content */}
        <div className="rounded-xl border border-zinc-200 bg-white shadow-sm dark:border-zinc-700 dark:bg-zinc-900 overflow-hidden">
          {/* Executive Summary */}
          <div className="px-6 py-6 sm:px-8 border-b border-zinc-200 dark:border-zinc-700">
            <h2 className="text-lg font-semibold text-zinc-900 dark:text-zinc-100 mb-4 flex items-center gap-2">
              <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-zinc-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
              Executive Summary
            </h2>
            <div className="prose prose-sm prose-zinc dark:prose-invert max-w-none">
              <p className="text-sm text-zinc-600 dark:text-zinc-400 leading-relaxed">
                Q1 2026 demonstrated strong revenue growth across all primary channels, with total revenue reaching
                <span className="font-semibold text-zinc-900 dark:text-zinc-100"> $48,235</span>, a
                <span className="font-semibold text-emerald-600 dark:text-emerald-400"> 12.5% increase</span> compared to Q4 2025.
                Client acquisition remained healthy with 23 new clients onboarded, while retention stabilized at 94.2%.
                The direct sales channel continues to be the primary revenue driver at 40% of total revenue, followed by
                referral (25%), organic (20%), and paid channels (15%).
              </p>
              <p className="text-sm text-zinc-600 dark:text-zinc-400 leading-relaxed mt-3">
                Notable challenges include a slight decline in average deal size (-2.1%), which warrants attention in Q2.
                However, the reduction in sales cycle duration by 3 days indicates improved efficiency in the pipeline.
                Overall, the business is on track to meet or exceed the annual revenue target of $200,000.
              </p>
            </div>
          </div>

          {/* Key Metrics Table */}
          <div className="px-6 py-6 sm:px-8 border-b border-zinc-200 dark:border-zinc-700">
            <h2 className="text-lg font-semibold text-zinc-900 dark:text-zinc-100 mb-4 flex items-center gap-2">
              <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-zinc-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
              </svg>
              Key Metrics
            </h2>
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead>
                  <tr className="border-b border-zinc-200 dark:border-zinc-700">
                    <th className="text-left pb-3 text-xs font-semibold uppercase tracking-wider text-zinc-500 dark:text-zinc-400">
                      Metric
                    </th>
                    <th className="text-right pb-3 text-xs font-semibold uppercase tracking-wider text-zinc-500 dark:text-zinc-400">
                      Value
                    </th>
                    <th className="text-right pb-3 text-xs font-semibold uppercase tracking-wider text-zinc-500 dark:text-zinc-400">
                      Change
                    </th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-zinc-100 dark:divide-zinc-800">
                  {keyMetrics.map((m) => (
                    <tr key={m.metric}>
                      <td className="py-3 text-sm text-zinc-700 dark:text-zinc-300">{m.metric}</td>
                      <td className="py-3 text-sm font-semibold text-zinc-900 dark:text-zinc-100 text-right">
                        {m.value}
                      </td>
                      <td className="py-3 text-right">
                        <span
                          className={`inline-flex items-center text-xs font-semibold ${
                            m.positive ? 'text-emerald-600 dark:text-emerald-400' : 'text-red-600 dark:text-red-400'
                          }`}
                        >
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            className={`h-3 w-3 mr-0.5 ${m.positive ? '' : 'rotate-180'}`}
                            fill="none"
                            viewBox="0 0 24 24"
                            stroke="currentColor"
                            strokeWidth={2}
                          >
                            <path strokeLinecap="round" strokeLinejoin="round" d="M5 15l7-7 7 7" />
                          </svg>
                          {m.change}
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* Chart Placeholder */}
          <div className="px-6 py-6 sm:px-8 border-b border-zinc-200 dark:border-zinc-700">
            <h2 className="text-lg font-semibold text-zinc-900 dark:text-zinc-100 mb-4 flex items-center gap-2">
              <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-zinc-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M7 12l3-3 3 3 4-4M8 21l4-4 4 4M3 4h18M4 4h16v12a1 1 0 01-1 1H5a1 1 0 01-1-1V4z" />
              </svg>
              Revenue Trend
            </h2>
            {/* CSS-only area chart visualization */}
            <div className="rounded-lg border border-zinc-100 dark:border-zinc-800 bg-zinc-50 dark:bg-zinc-800/50 p-6">
              <div className="flex items-end justify-between gap-1.5 h-40">
                {[32, 41, 38, 52, 48, 61, 55, 70, 64, 78, 72, 85].map((val, i) => (
                  <div key={i} className="flex-1 flex flex-col items-center gap-1">
                    <div
                      className="w-full rounded-t-sm bg-gradient-to-t from-emerald-500 to-emerald-400 dark:from-emerald-600 dark:to-emerald-500 transition-all duration-300 hover:from-emerald-400 hover:to-emerald-300"
                      style={{ height: `${(val / 85) * 100}%` }}
                    />
                  </div>
                ))}
              </div>
              <div className="flex justify-between mt-2">
                {['J', 'F', 'M', 'A', 'M', 'J', 'J', 'A', 'S', 'O', 'N', 'D'].map((m, i) => (
                  <span key={i} className="flex-1 text-center text-[10px] text-zinc-400 dark:text-zinc-500">
                    {m}
                  </span>
                ))}
              </div>
            </div>
          </div>

          {/* Recommendations */}
          <div className="px-6 py-6 sm:px-8 border-b border-zinc-200 dark:border-zinc-700">
            <h2 className="text-lg font-semibold text-zinc-900 dark:text-zinc-100 mb-4 flex items-center gap-2">
              <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-zinc-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
              </svg>
              Recommendations
            </h2>
            <div className="space-y-3">
              {recommendations.map((rec, i) => (
                <div key={i} className="flex items-start gap-3 rounded-lg border border-zinc-100 dark:border-zinc-800 bg-zinc-50 dark:bg-zinc-800/50 p-4">
                  <span className="flex-shrink-0 flex items-center justify-center w-6 h-6 rounded-full bg-emerald-100 dark:bg-emerald-500/20 text-emerald-600 dark:text-emerald-400 text-xs font-bold">
                    {i + 1}
                  </span>
                  <p className="text-sm text-zinc-600 dark:text-zinc-400 leading-relaxed">{rec}</p>
                </div>
              ))}
            </div>
          </div>

          {/* Footer */}
          <div className="px-6 py-5 sm:px-8 bg-zinc-50 dark:bg-zinc-800/30">
            <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2 text-xs text-zinc-400 dark:text-zinc-500">
              <div className="flex items-center gap-4">
                <span>Report ID: {id}</span>
                <span>Generated: {report.date}</span>
                <span>By: {report.author}</span>
              </div>
              <div className="flex items-center gap-1">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-3.5 w-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
                <span>This report was auto-generated by Gravitiq Analytics Engine v2.4</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
